package com.oreilly.myviewmodeldemo

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import com.oreilly.myviewmodeldemo.ui.main.MainFragment

// Generated by ViewModel/Fragment Activity wizard
class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.main_activity)
        if (savedInstanceState == null) {
            supportFragmentManager.beginTransaction()
                    .replace(R.id.container, MainFragment.newInstance())
                    .commitNow()
        }
    }
}